const API_URL_DEVELOPMENT = "/api/auth";
const API_URL_PRODUCTION = "https://mentor-hub.runasp.net/api/auth";

const ENDPOINT = {
  LOGIN: "login",
  LOGOUT: "logout",
  GOOGLE_LOGIN: "login/google",
  GOOGLE_LOGIN_CALLBACK: "login/google/callback",
  CHANGE_PASSWORD: "change-password",
};

const development = {
  LOGIN_USER: `${API_URL_DEVELOPMENT}/${ENDPOINT.LOGIN}`,
  LOGOUT_USER: `${API_URL_DEVELOPMENT}/${ENDPOINT.LOGOUT}`,
  GOOGLE_LOGIN: `${API_URL_DEVELOPMENT}/${ENDPOINT.GOOGLE_LOGIN}`,
  GOOGLE_LOGIN_CALLBACK: `${API_URL_DEVELOPMENT}/${ENDPOINT.GOOGLE_LOGIN_CALLBACK}`,
  CHANGE_PASSWORD: `${API_URL_DEVELOPMENT}/${ENDPOINT.CHANGE_PASSWORD}`,
};

const production = {
  LOGIN_USER: `${API_URL_PRODUCTION}/${ENDPOINT.LOGIN}`,
  LOGOUT_USER: `${API_URL_PRODUCTION}/${ENDPOINT.LOGOUT}`,
  GOOGLE_LOGIN: `${API_URL_PRODUCTION}/${ENDPOINT.GOOGLE_LOGIN}`,
  GOOGLE_LOGIN_CALLBACK: `${API_URL_PRODUCTION}/${ENDPOINT.GOOGLE_LOGIN_CALLBACK}`,
  CHANGE_PASSWORD: `${API_URL_PRODUCTION}/${ENDPOINT.CHANGE_PASSWORD}`,
};

const urlAuth =
  import.meta.env.MODE === "development" ? development : production;

export default urlAuth;
