@MentorHup_HostAddress = https://localhost:7020

GET {{MentorHup_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{MentorHup_HostAddress}}/api/mentees/login
Content-Type: application/json

{
  "email": "khaled1@string.com",
  "password": "khaled2@string.com"
}



###

POST {{MentorHup_HostAddress}}/api/mentees/register
Content-Type: application/json

{
  "name": "a7med",
  "gender": "Male",
  "email": "a7med12@string.com",
  "password": "string@123"
}





###

POST {{MentorHup_HostAddress}}/api/mentors/login
Content-Type: application/json

{
  //MentorLoginRequest
}

###

POST {{MentorHup_HostAddress}}/api/mentors/register
Content-Type: application/json

{
  //MentorRegisterRequest
}


###

GET https://localhost:7020/api/mentors

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImM1N2MyZTlmLTBmY2YtNDQ2Yy1iOWE3LTdhNTU1YjJkMmE1MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImtoYWxlZDFAc3RyaW5nLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6Ik1lbnRlZSIsImV4cCI6MTc1Njc4MDkxMywiaXNzIjoiTWVudG9ySHVwQVBJIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCxodHRwczovL2xvY2FsaG9zdCJ9.iDiQwnTxLEpwZ-FKBGSaixKF2J7d6dRI255_EOUI_0k